[package]
name = "sqore-dialog-builder"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/QueenOfSquiggles/sqore-dialog-builder"

[dependencies]
eframe = "0.25.0"
egui_extras = {version="0.25.0", features = ["all_loaders"] }
image = "0.24"
rfd = "0.11.0"
